name: Build Windows Game

on:
  workflow_dispatch:
    inputs:
      build-defines:
        type: string
        default: '-DGITHUB_BUILD'

jobs:
  build-game:
    runs-on: windows-latest

    defaults:
      run:
        shell: bash

    env:
      BUILD_DEFINES: ${{ github.event.inputs.build-defines || '-DGITHUB_BUILD' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Setup build environment
        uses: ./.github/actions/setup-haxe

      - name: Setup HXCPP
        run: |
          cd .haxelib/hxcpp/git/tools/hxcpp
          haxe compile.hxml
          cd ../../../../..

      - name: Build game
        run: haxelib run lime build windows -v -release $BUILD_DEFINES

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-windows
          path: export/release/windows/bin/
